# Generated by Django 5.1.3 on 2024-11-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('a_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('a_email', models.CharField(max_length=254, unique=True)),
                ('a_name', models.CharField(max_length=100, unique=True)),
                ('a_password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'admin_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorpusTable',
            fields=[
                ('language_profeciency', models.CharField()),
                ('corpus_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'corpus_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTable',
            fields=[
                ('sen_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_data', models.CharField()),
                ('t_target_data', models.CharField(blank=True, null=True)),
                ('r_target_data', models.CharField(blank=True, null=True)),
                ('batch_id', models.IntegerField()),
                ('minor_job_id', models.IntegerField(blank=True, null=True)),
                ('major_job_id', models.IntegerField()),
                ('t_flag', models.CharField(max_length=1)),
                ('r_flag', models.CharField(max_length=1)),
                ('corpus_id', models.TextField()),
                ('priority', models.CharField()),
                ('t_assigned', models.CharField(max_length=1)),
                ('r_assigned', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'job_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationTable',
            fields=[
                ('user_name', models.CharField()),
                ('email', models.CharField(primary_key=True, serialize=False)),
                ('password', models.CharField()),
                ('user_type', models.CharField()),
                ('language_profeciency', models.CharField()),
                ('org_details', models.TextField()),
                ('flag', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'registration_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=20)),
                ('r_name', models.CharField()),
                ('password', models.CharField()),
                ('email', models.CharField()),
                ('language_profeciency', models.CharField()),
                ('major_job_id', models.IntegerField(blank=True, null=True)),
                ('minor_job_id', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('batch_range', models.CharField(blank=True, null=True)),
                ('job_assigned', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'reviewer_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TranslatorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=20)),
                ('t_name', models.CharField()),
                ('password', models.CharField()),
                ('email', models.CharField()),
                ('language_profeciency', models.CharField()),
                ('major_job_id', models.IntegerField(blank=True, null=True)),
                ('minor_job_id', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('batch_range', models.CharField(blank=True, null=True)),
                ('t_review', models.CharField(blank=True, null=True)),
                ('corpus_id', models.TextField()),
                ('job_assigned', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'translator_table',
                'managed': False,
            },
        ),
    ]
