# Generated by Django 4.2.16 on 2024-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorTable',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField()),
            ],
            options={
                'db_table': 'major_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RLogTable',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('batch_range', models.CharField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('login', models.DateTimeField(blank=True, null=True)),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('log_duration', models.DateTimeField(blank=True, null=True)),
                ('module_access_timestamp', models.DateTimeField(blank=True, null=True)),
                ('module_submission_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'r_log_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TLogTable',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('t_id', models.CharField(blank=True, null=True)),
                ('batch_range', models.CharField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('login', models.DateTimeField(blank=True, null=True)),
                ('logout', models.DateTimeField(blank=True, null=True)),
                ('log_duration', models.DateTimeField(blank=True, null=True)),
                ('module_access_timestamp', models.DateTimeField(blank=True, null=True)),
                ('module_submission_timestamp', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_log_table',
                'managed': False,
            },
        ),
    ]
